abstract class SystemVariablesState{}

class SystemVariablesFetchComplete extends SystemVariablesState{}
class SystemVariablesFetchError extends SystemVariablesState{}
class SystemVariablesFetchProgress extends SystemVariablesState{}
class SystemVariablesFetchNone extends SystemVariablesState{}